name: app_ecopost
description: "A new Flutter project."
# Prevent accidental publishing to pub.dev (private package).
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
# Versioning: Format is `<major>.<minor>.<patch>+<build_number>`.
version: 1.0.0+1
environment:
  sdk: ^3.5.3
# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8 # Cupertino Icons for iOS-style icons
  path_provider: ^2.1.5 # Provides access to platform-specific file paths
  sqlite3: ^2.7.5 # SQLite database support
  provider: ^6.1.4 # State management
  intl: ^0.20.2 # Internationalization and localization support
  flutter_dotenv: ^5.2.1 # Loads environment variables from a .env file
  sqlite3_flutter_libs: ^0.5.32 # Native SQLite libraries for Flutter
  onboarding: ^4.0.2 # Onboarding screen support
  shared_preferences: ^2.5.3 # Persistent storage for key-value pairs
  flutter_native_splash: ^2.4.4 # Splash screen configuration
  location: ^7.0.1
  permission_handler: ^12.0.0+1
  #geolocator: ^14.0.0
  package_info_plus: ^8.3.0
  another_flutter_splash_screen: ^1.2.1
  latlong2: ^0.9.1
  connectivity_plus: ^6.1.3
  flutter_map: ^7.0.2
# Configuration for `flutter_native_splash` package
flutter_native_splash:
  color: "#FBB232" # Background color for the splash screen
  image: "assets/logo_aplicativo.png" # Optional splash screen image
  android: true # Enable splash screen for Android
  ios: true # Enable splash screen for iOS
# Configuration for `flutter_launcher_icons` package
flutter_icons:
  image_path: "assets/logo_aplicativo.png" # Path to the icon image
  ios: true # Generate icons for iOS
  android: true # Generate icons for Android
  adaptive_icon_foreground: "assets/logo_aplicativo.png" # Foreground image for adaptive icons
  adaptive_icon_background: "#FFFFFF" # Background color for adaptive icons
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0 # Linting rules for better coding practices
# Flutter-specific configurations
flutter:
  uses-material-design: true # Include Material Design icons
  # Assets to include in the application
  assets:
    - .env # Environment variables file
    - assets/logo_sem_fundo.png # Additional assets
    - assets/logo_aplicativo.png # Icon and splash screen image

# Uncomment and configure if you want to add custom fonts
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
